package horzsolt.petprojects.koala.model;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.PropertySource;

@PropertySource("classpath:config.properties")
public class Constants {
	@Value("${koala.serializationroot}")
	public static String serializationRoot;

	public static final String[] favs = { "BUUREN", "DIGWEED", "SAIZ", "PETETONG", "SANDER", "GUYJ", "NICKWARREN",
			"SASHA", "MACEOPLEX", "ADVISOR", "CHART", "NEWIK", "MUSICKILLERS", "MINILOGUE", "PIGDAN", "WATERMAT",
			"SHOWTEK", "MANTEY", "TODDTERJE", "MATTZO", "WESTBAM", "BERGHEAU", "BOOKASHADE", "BLIZZARD", "RANK1",
			"KOLETZKI", "KALKBRENNER", "REXMUNDI", "ATB", "DASHBERLIN", "ORJANNIELSEN", "GARETHEMERY", "BLOMQVIST",
			"NADJALIND", "EXTRAWELT", "SCAVO", "KOLLEKTIV", "BERLIN", "DAHLBACK", "BENASSI", "VARIOUS", "COMPILED",
			"GUETTA", "HARRIS", "DUMONT", "CLAPTONE", "ZEDD", "DVBBS", "MARKKNIGHT", "SHEPARD", "FEDDELEGRAND",
			"ROGERSHAH", "KYAU", "ABOVE", "BEST", "SELECT", "EXCLUSIVE", "TALEOFUS", "DIXON", "HEIDI", "HAWTIN",
			"GARRIX", "BENKLOCK", "TROXLER", "EATSEVERYTHING", "COLLECTION", "HOTSINCE", "MARCOCAROLA", "KLARTRAUM",
			"MAYAJANECOL", "SVENVATH", "JACKMASTER", "JAYLUMEN", "NINAKRAVIZ", "GARNIER", "LIEBING", "DAMIANLAZARUS",
			"CARLCOX", "LUCIANO", "LEEBURRIDGE", "JORISVOORN", "BUTCH", "ZABIELA", "CATZ", "CATTANEO", "JEFFMILLS",
			"JUSTINMARTIN", "LAWLER", "PACOOSUNA", "TANZMANN", "DEETRON", "DEEP", "VOLUME", "BENNFINN", "TIMOMAAS",
			"PICKS", "FABRIC", "GLOBALUNDERGROUND", "MOBY", "SERIES", "HOXTON", "ESSENTIAL", "AUDIO", "MOONBEAM",
			"RATOP", "TRACKS", "UNMIXED", "BUDAI", "HUNGARY", "BUDAPEST", "SOUNDS", "PODCAST", "MANTZUR", "VANNELLI",
			"HAWTIN", "TRENTEM", "CHYMERA", "SCUBA", "GUYGERBER", "ZUSAMMENKLANG", "EULBERG, HAZENDONK",
			"RILEYREINHOLD", "ABOVE", "RESIDENT", "ADVISOR", "RHAB", "RIVERA", "NICKYROMERO", "MARKUSSCHULZ", "DOORN",
			"BASSJACKER", "BEUKEN", "MAJORLAZER", "UMMET", "LIKEMIKE", "NOVELLI", "COSMICGATE", "KYGO", "CALVINHARRIS",
			"SYGMA", "VEKONYZ", "ALESSO", "GAIA", "ZHU", "JEROMEISMA", "BERGHEAU", "EMPIREOFTHESUN", "DYK", "NOVELLI",
			"DEYNHOVEN", "BOBINA", "THRILLSEEKERS", "ALYFILA", "JOHNASKEW", "MATTDAREY", "OMNIA" };

}
